spring:
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database: MYSQL
        show-sql: true
        properties:
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
            hibernate.cache.region.factory_class: com.toll.userinfo.config.hazelcast.HazelcastCacheRegionFactory
            hibernate.cache.use_minimal_puts: true
            hibernate.cache.hazelcast.use_lite_member: true
    mail:
        host: localhost
        port: 25
        username:
        password:
    messages:
        cache-seconds: 1
    thymeleaf:
        cache: false
        
EmailForScheduled:
    scheduledJob:
        cron: 0 */5 * * * ?
        
functionsettings:
    #url: https://api.myjson.com/bins/16ajrn
    #url: https://api.myjson.com/bins/1eg7iz
liquibase:
    enabled: false
    contexts: dev

server:
    port: 8080